# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3118e45d93328359ebc2fa0734374a306d26a6ca19969bc4ba921c8b691f7ef92fdd41c4115745055d965db27417f7ef3fd2d3b6c3c26f2b9fd5954c029bd1a5

test:
  secret_key_base: e75ddbd28749d4e295993ae327506c04b4d27f8feda3968ef6b2cd695210499ed9d454bc2a4a14941999cff22bb3265e80c13ccae58cb50a9cb552a52cea038d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
